spring:
  application:
    name: ai-travel-planner
  datasource:
    url: jdbc:postgresql://localhost:5432/travelplanner
    username: postgres
    password: postgres
  profiles:
    include: oauth

server:
  port: 8080

# Frontend URL for CORS
frontend:
  url: http://localhost:3000