spring:
  application:
    name: ai-travel-planner
  datasource:
    url: jdbc:postgresql://localhost:5432/travelplanner
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  profiles:
    include: oauth

server:
  port: 8080

# Frontend URL for CORS
frontend:
  url: http://localhost:3000